name: Deploy

on:
  push:
    branches: ["main", "fix-deploy"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Setup Elm
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install create-elm-app -g

      - name: Build app
        run: elm-app build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build/*"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
